#!/usr/bin/env bash
#
# build-arch.sh —— 将 MD3L 打包为标准 Arch Linux 软件包 (pkg.tar.zst)
#
# 由于当前环境没有 makepkg/bsdtar，本脚本手动完成以下工作：
#   1. (可选) 用 gradle 构建最新的 .deb
#   2. 解包 .deb 得到 opt/md3l 目录树
#   3. 补充系统级 .desktop 与图标 (usr/share/...)
#   4. 生成符合 pacman 规范的 .PKGINFO 与 gzip 压缩的 .MTREE
#   5. 用 fakeroot + tar + zstd 打包为 <pkg>.pkg.tar.zst
#
# 用法：
#   ./build-arch.sh                # 重新用 gradle 构建 deb 后打包
#   ./build-arch.sh --use-deb PATH # 复用指定的 deb，跳过 gradle 构建
#
set -euo pipefail

# ---------------- 包元信息 ----------------
pkgname="md3l"
pkgdesc="MD3L - A modern Minecraft launcher (Linux Edition)"
pkgver="1.4.4.a"
pkgrel="1"
arch="x86_64"
url=""
license="custom"
packager="MD3L"

# ---------------- 解析参数 ----------------
DEB_PATH=""
BUILD_DEB=1
while [[ $# -gt 0 ]]; do
    case "$1" in
        --use-deb)
            DEB_PATH="$2"; BUILD_DEB=0; shift 2 ;;
        *)
            echo "未知参数: $1" >&2; exit 1 ;;
    esac
done

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

# ---------------- 1. 构建 deb ----------------
if [[ "$BUILD_DEB" -eq 1 ]]; then
    echo ">>> 使用 gradle 构建 deb ..."
    ./gradlew packageDeb --console=plain
    DEB_PATH="$(find build/compose/binaries/main/deb -maxdepth 1 -name '*.deb' -printf '%T@ %p\n' \
        | sort -nr | head -1 | cut -d' ' -f2-)"
fi

if [[ -z "$DEB_PATH" || ! -f "$DEB_PATH" ]]; then
    echo "!!! 找不到 deb 文件: '$DEB_PATH'" >&2
    exit 1
fi
echo ">>> 使用 deb: $DEB_PATH"

# ---------------- 2. 准备工作目录 ----------------
WORK="$(mktemp -d)"
PKGDIR="$WORK/pkg"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$PKGDIR"

echo ">>> 解包 deb 内容 ..."
dpkg-deb -x "$DEB_PATH" "$PKGDIR"

# 只保留安装内容（opt/ 等），移除 deb 特有的控制目录（若有）
rm -rf "$PKGDIR/DEBIAN" 2>/dev/null || true

# ---------------- 3. 系统级 desktop + 图标 ----------------
echo ">>> 写入系统级 .desktop 与图标 ..."
install -d "$PKGDIR/usr/share/applications"
cat > "$PKGDIR/usr/share/applications/md3l.desktop" <<'DESKTOP'
[Desktop Entry]
Name=MD3L
Comment=MD3L - A modern Minecraft launcher (Linux Edition)
Exec=/opt/md3l/bin/MD3L
Icon=md3l
Terminal=false
Type=Application
Categories=Game;
MimeType=
DESKTOP

# 图标：优先使用源码图标，其次使用 deb 内自带图标
ICON_DST_DIR="$PKGDIR/usr/share/icons/hicolor/128x128/apps"
install -d "$ICON_DST_DIR"
if [[ -f "$ROOT_DIR/src/main/resources/app_icon.png" ]]; then
    install -m644 "$ROOT_DIR/src/main/resources/app_icon.png" "$ICON_DST_DIR/md3l.png"
elif [[ -f "$PKGDIR/opt/md3l/lib/MD3L.png" ]]; then
    install -m644 "$PKGDIR/opt/md3l/lib/MD3L.png" "$ICON_DST_DIR/md3l.png"
fi

# ---------------- 4. 生成 .PKGINFO ----------------
echo ">>> 生成 .PKGINFO ..."
INSTALL_SIZE="$(du -sb "$PKGDIR" | cut -f1)"
BUILDDATE="$(date +%s)"
cat > "$PKGDIR/.PKGINFO" <<PKGINFO
# Generated by build-arch.sh
pkgname = ${pkgname}
pkgbase = ${pkgname}
pkgver = ${pkgver}-${pkgrel}
pkgdesc = ${pkgdesc}
url = ${url}
builddate = ${BUILDDATE}
packager = ${packager}
size = ${INSTALL_SIZE}
arch = ${arch}
license = ${license}
PKGINFO

# ---------------- 5. 生成 .MTREE ----------------
# .MTREE 是 gzip 压缩的 mtree 文本，供 pacman 做文件完整性校验。
echo ">>> 生成 .MTREE ..."
MTREE_TXT="$WORK/mtree.txt"
{
    echo "#mtree"
    echo "/set type=file uid=0 gid=0 mode=644"
    # 遍历包内所有条目（不含 .MTREE 自身），路径以 ./ 开头
    (cd "$PKGDIR" && find . -mindepth 1 -printf '%P\n' | LC_ALL=C sort) | while IFS= read -r rel; do
        full="$PKGDIR/$rel"
        # mtree 需要对空格等特殊字符做 vis 转义，这里对空格转义为 \040
        esc_path="./$(printf '%s' "$rel" | sed 's/ /\\040/g')"
        mode="$(stat -c '%a' "$full")"
        mtime="$(stat -c '%Y' "$full")"
        if [[ -L "$full" ]]; then
            target="$(readlink "$full")"
            esc_target="$(printf '%s' "$target" | sed 's/ /\\040/g')"
            printf '%s time=%s.0 mode=%s type=link link=%s\n' \
                "$esc_path" "$mtime" "$mode" "$esc_target"
        elif [[ -d "$full" ]]; then
            printf '%s time=%s.0 mode=%s type=dir\n' \
                "$esc_path" "$mtime" "$mode"
        else
            size="$(stat -c '%s' "$full")"
            md5="$(md5sum "$full" | cut -d' ' -f1)"
            sha="$(sha256sum "$full" | cut -d' ' -f1)"
            printf '%s time=%s.0 mode=%s size=%s md5digest=%s sha256digest=%s\n' \
                "$esc_path" "$mtime" "$mode" "$size" "$md5" "$sha"
        fi
    done
} > "$MTREE_TXT"
gzip -9 -c -n "$MTREE_TXT" > "$PKGDIR/.MTREE"

# ---------------- 6. 打包 ----------------
OUTPUT="$ROOT_DIR/${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst"
echo ">>> 打包为 $OUTPUT ..."

# 构建 tar 成员列表：.PKGINFO 必须最先，其次 .MTREE，然后其余内容
MEMBERS_FILE="$WORK/members.txt"
{
    echo ".PKGINFO"
    echo ".MTREE"
    (cd "$PKGDIR" && find . -mindepth 1 -printf '%P\n' \
        | grep -vE '^\.(PKGINFO|MTREE)$' | LC_ALL=C sort)
} > "$MEMBERS_FILE"

# fakeroot 确保归档内 uid/gid 归零；tar 从 members 列表读取顺序
fakeroot -- bash -c '
    set -euo pipefail
    cd "$1"
    tar --owner=0 --group=0 --no-recursion \
        --numeric-owner \
        -cf - -T "$2" \
    | zstd -c -T0 -19 --long > "$3"
' _ "$PKGDIR" "$MEMBERS_FILE" "$OUTPUT"

echo ">>> 完成: $OUTPUT"
ls -lh "$OUTPUT"
